list:
    path: /{page}
    controller: App\Controller\ProductController::list
    requirements:
        page: '\d+'
    defaults:
      page: 1

add_cart_product:
    path: /addProduct/{id}
    controller: App\Controller\CartController::add

show:
    path: /product/{id}
    controller: App\Controller\ProductController::show
    requirements:
        slug: '[\S]+'

edit:
    path: /edit/{id}
    controller: App\Controller\ProductController::edit

create:
    path: /create
    controller: App\Controller\ProductController::create

editCategory:
    path: /edit/category/{id}
    controller: App\Controller\CartController::editCat

product_show:
    path: /show/{slug}
    controller: App\Controller\ProductController::showCustom
    requirements:
        slug: '[\S]+'

api_login_check:
    path: /api/login_check

